// @dino-atlas/types - Shared type definitions
// Based on datamodel.md — aligned with PocketBase schema + screen needs

// ── Enums ──

export type Period = "Trias" | "Jura" | "Kreide";
export type Diet = "Pflanzenfresser" | "Fleischfresser" | "Allesfresser";
export type Rarity = "common" | "uncommon" | "rare" | "epic" | "legendary";
export type Biom = "desert" | "jungle" | "ice" | "ocean";

export type ExpeditionStatus =
  | "intro"
  | "excavation"
  | "puzzle"
  | "identify"
  | "discovery"
  | "offline"
  | "complete";

export type MinigameType =
  | "quiz"
  | "size_sort"
  | "timeline"
  | "food_match"
  | "shadow_guess";

export type OfflineTaskType = "draw" | "build" | "measure" | "find";

// ── Family & Auth ──

export interface Family {
  id: string;
  name: string;
  createdAt: string;
}

export interface User {
  id: string;
  email: string;
  familyId: string;
}

export interface Player {
  id: string;
  familyId: string;
  name: string;
  avatarEmoji: string;
  birthYear: number;
  interests: string[];
  level: number;
  dinosDiscovered: number;
  minigamesRemaining: number;
}

// ── Dino Species (Stammdaten) ──

export interface DinoFact {
  icon: string;
  label: string;
  value: string;
  sub?: string;
  story: string;
  audioUrl?: string;
}

export interface QuizQuestion {
  question: string;
  options: { label: string; emoji: string; correct: boolean }[];
  explanation: string;
}

export interface FoodOption {
  id: string;
  emoji: string;
  label: string;
  correct: boolean;
}

export interface DinoSpecies {
  id: string;
  slug: string;
  displayNameDe: string;
  scientificName: string;

  // Classification
  period: Period;
  periodStartMya: number;
  periodEndMya: number;
  diet: Diet;
  lengthM: number;
  weightKg: number;
  continent: string;
  continentPosition: { left: string; top: string };
  rarity: Rarity;

  // Texts (generated by Gemini)
  kidSummary: string;
  funFact: string;
  sizeComparison: string;

  // Images (PocketBase file URLs)
  imageComic: string;
  imageReal: string;
  imageSkeleton: string;
  imageShadow: string;

  // Audio (PocketBase file URLs)
  audioName?: string;
  audioSteckbrief?: string;

  // Structured data (JSON in PocketBase)
  facts: DinoFact[];
  quizQuestions: QuizQuestion[];
  foodOptions: FoodOption[];
  identifyHints: Record<string, string>;
}

// ── Expedition ──

export interface Expedition {
  id: string;
  playerId: string;
  dinoSpeciesId: string;
  date: string;
  biom: Biom;
  status: ExpeditionStatus;
  excavationTimeMs?: number;
  puzzleTimeMs?: number;
  identifyAttempts?: number;
  offlineTaskType?: OfflineTaskType;
  offlineTaskAccepted?: boolean;
}

// ── Museum ──

export interface MuseumEntry {
  id: string;
  playerId: string;
  dinoSpeciesId: string;
  discoveredAt: string;
  stars: number;
  artworkPhoto?: string;
  artworkAiFeedback?: string;
  favorite: boolean;
}

// ── Stories ──

export interface WordTimestamp {
  word: string;
  start: number;
  end: number;
}

export interface Story {
  id: string;
  familyId: string;
  date: string;
  title: string;
  playerDinos: { playerId: string; dinoSpeciesId: string }[];
  storyText: string;
  audioUrl?: string;
  timestamps?: WordTimestamp[];
}

// ── Mini-Games ──

export interface MinigameSession {
  id: string;
  playerId: string;
  gameType: MinigameType;
  dinoSpeciesIds: string[];
  score: number;
  starsEarned: number;
  timeMs: number;
  completedAt: string;
}

// ── Budget ──

export interface DailyBudget {
  id: string;
  playerId: string;
  date: string;
  expeditionsUsed: number;
  expeditionsMax: number;
  minigamesUsed: number;
  minigamesMax: number;
  eveningSessionDone: boolean;
  isTired: boolean;
}

export interface BudgetReset {
  id: string;
  playerId: string;
  date: string;
  resetByUserId: string;
  mathQuestion: string;
  mathAnswerGiven: string;
  resetAt: string;
}

// ── Offline Tasks ──

export interface OfflineTask {
  id: string;
  expeditionId: string;
  taskType: OfflineTaskType;
  dinoSpeciesId: string;
  acceptedAt?: string;
  photoUploaded: boolean;
  photo?: string;
  aiFeedback?: string;
}

// ── AI Tracking ──

export interface AiModel {
  id: string;
  provider: string;
  modelId: string;
  displayName: string;
  capabilities: string[];
  pricePer1mInputTokensUsd: number;
  pricePer1mOutputTokensUsd: number;
  pricePerImageUsd: number;
  isActive: boolean;
}

export interface AiUsageLog {
  id: string;
  jobId?: string;
  triggeredBy: "admin" | "app" | "worker";
  triggerContext: string;
  modelId: string;
  operation: string;
  inputTokens: number;
  outputTokens: number;
  imageCount: number;
  costEstimateUsd: number;
  durationMs: number;
  success: boolean;
  errorMessage?: string;
  createdAt: string;
}

// ── Jobs ──

export type JobStatus = "pending" | "processing" | "completed" | "failed";

export interface Job {
  id: string;
  type: string;
  status: JobStatus;
  createdAt: string;
  completedAt?: string;
  error?: string;
}

// ── UI Contracts ──

export interface MinigameResult {
  score: number;
  starsEarned: number;
  timeMs: number;
}

export interface DifficultyLevel {
  puzzlePieces: number;
  quizOptions: number;
  showOutline: boolean;
  hintsEnabled: boolean;
}
