FROM rust:1.87
WORKDIR /app
RUN cargo install cargo-watch --locked
COPY Cargo.toml ./
RUN mkdir src && echo 'fn main() {}' > src/main.rs && cargo build && rm -rf src
COPY src ./src
CMD ["cargo", "watch", "-x", "run"]
