use serde::Serialize;

/// Base dino data for seeding (before AI generation)
#[derive(Debug, Serialize, Clone)]
pub struct DinoSeed {
    pub slug: String,
    pub display_name_de: String,
    pub scientific_name: String,
    pub period: String,
    pub period_start_mya: u32,
    pub period_end_mya: u32,
    pub diet: String,
    pub length_m: f32,
    pub weight_kg: f32,
    pub continent: String,
    pub rarity: String,
    pub habitat_description: String,
}

pub fn all_dino_slugs() -> Vec<String> {
    all_dinos().into_iter().map(|d| d.slug).collect()
}

pub fn all_dinos() -> Vec<DinoSeed> {
    vec![
        DinoSeed {
            slug: "triceratops".into(),
            display_name_de: "Triceratops".into(),
            scientific_name: "Dreihorn-Gesicht".into(),
            period: "Kreide".into(),
            period_start_mya: 68,
            period_end_mya: 66,
            diet: "Pflanzenfresser".into(),
            length_m: 9.0,
            weight_kg: 12000.0,
            continent: "Nordamerika".into(),
            rarity: "rare".into(),
            habitat_description: "Lush Cretaceous period forest with ferns and conifers.".into(),
        },
        DinoSeed {
            slug: "tyrannosaurus-rex".into(),
            display_name_de: "T-Rex".into(),
            scientific_name: "Tyrannenechse".into(),
            period: "Kreide".into(),
            period_start_mya: 68,
            period_end_mya: 66,
            diet: "Fleischfresser".into(),
            length_m: 12.0,
            weight_kg: 9000.0,
            continent: "Nordamerika".into(),
            rarity: "legendary".into(),
            habitat_description: "Dense subtropical forest with towering conifers.".into(),
        },
        DinoSeed {
            slug: "stegosaurus".into(),
            display_name_de: "Stegosaurus".into(),
            scientific_name: "Dachechse".into(),
            period: "Jura".into(),
            period_start_mya: 155,
            period_end_mya: 150,
            diet: "Pflanzenfresser".into(),
            length_m: 9.0,
            weight_kg: 5000.0,
            continent: "Nordamerika".into(),
            rarity: "uncommon".into(),
            habitat_description: "Open Jurassic plains with scattered cycads and ferns.".into(),
        },
        DinoSeed {
            slug: "brachiosaurus".into(),
            display_name_de: "Brachiosaurus".into(),
            scientific_name: "Armechse".into(),
            period: "Jura".into(),
            period_start_mya: 154,
            period_end_mya: 150,
            diet: "Pflanzenfresser".into(),
            length_m: 26.0,
            weight_kg: 56000.0,
            continent: "Nordamerika".into(),
            rarity: "epic".into(),
            habitat_description: "Vast Jurassic floodplains with tall conifer forests.".into(),
        },
        DinoSeed {
            slug: "velociraptor".into(),
            display_name_de: "Velociraptor".into(),
            scientific_name: "Schneller Raeuber".into(),
            period: "Kreide".into(),
            period_start_mya: 75,
            period_end_mya: 71,
            diet: "Fleischfresser".into(),
            length_m: 2.0,
            weight_kg: 15.0,
            continent: "Asien".into(),
            rarity: "rare".into(),
            habitat_description: "Arid Cretaceous desert with sand dunes and scrub vegetation.".into(),
        },
        DinoSeed {
            slug: "ankylosaurus".into(),
            display_name_de: "Ankylosaurus".into(),
            scientific_name: "Gebogene Echse".into(),
            period: "Kreide".into(),
            period_start_mya: 68,
            period_end_mya: 66,
            diet: "Pflanzenfresser".into(),
            length_m: 6.5,
            weight_kg: 6000.0,
            continent: "Nordamerika".into(),
            rarity: "uncommon".into(),
            habitat_description: "Cretaceous woodland with dense undergrowth.".into(),
        },
        DinoSeed {
            slug: "pteranodon".into(),
            display_name_de: "Pteranodon".into(),
            scientific_name: "Zahnloser Fluegel".into(),
            period: "Kreide".into(),
            period_start_mya: 86,
            period_end_mya: 84,
            diet: "Fischfresser".into(),
            length_m: 6.0,
            weight_kg: 25.0,
            continent: "Nordamerika".into(),
            rarity: "rare".into(),
            habitat_description: "Coastal Cretaceous cliffs overlooking a shallow sea.".into(),
        },
        DinoSeed {
            slug: "spinosaurus".into(),
            display_name_de: "Spinosaurus".into(),
            scientific_name: "Dornenechse".into(),
            period: "Kreide".into(),
            period_start_mya: 99,
            period_end_mya: 93,
            diet: "Fleischfresser".into(),
            length_m: 15.0,
            weight_kg: 7400.0,
            continent: "Afrika".into(),
            rarity: "epic".into(),
            habitat_description: "Cretaceous river delta with mangrove-like vegetation.".into(),
        },
        DinoSeed {
            slug: "parasaurolophus".into(),
            display_name_de: "Parasaurolophus".into(),
            scientific_name: "Kammechse".into(),
            period: "Kreide".into(),
            period_start_mya: 76,
            period_end_mya: 73,
            diet: "Pflanzenfresser".into(),
            length_m: 10.0,
            weight_kg: 2500.0,
            continent: "Nordamerika".into(),
            rarity: "common".into(),
            habitat_description: "Lush Cretaceous wetlands with flowering plants.".into(),
        },
        DinoSeed {
            slug: "diplodocus".into(),
            display_name_de: "Diplodocus".into(),
            scientific_name: "Doppelbalken".into(),
            period: "Jura".into(),
            period_start_mya: 154,
            period_end_mya: 152,
            diet: "Pflanzenfresser".into(),
            length_m: 27.0,
            weight_kg: 16000.0,
            continent: "Nordamerika".into(),
            rarity: "epic".into(),
            habitat_description: "Semi-arid Jurassic savanna with scattered conifers.".into(),
        },
        DinoSeed {
            slug: "allosaurus".into(),
            display_name_de: "Allosaurus".into(),
            scientific_name: "Andere Echse".into(),
            period: "Jura".into(),
            period_start_mya: 155,
            period_end_mya: 150,
            diet: "Fleischfresser".into(),
            length_m: 9.5,
            weight_kg: 2300.0,
            continent: "Nordamerika".into(),
            rarity: "rare".into(),
            habitat_description: "Jurassic forest edges and open hunting grounds.".into(),
        },
        DinoSeed {
            slug: "mosasaurus".into(),
            display_name_de: "Mosasaurus".into(),
            scientific_name: "Maas-Echse".into(),
            period: "Kreide".into(),
            period_start_mya: 82,
            period_end_mya: 66,
            diet: "Fleischfresser".into(),
            length_m: 13.0,
            weight_kg: 15000.0,
            continent: "Europa".into(),
            rarity: "legendary".into(),
            habitat_description: "Deep Cretaceous ocean with coral reefs.".into(),
        },
        DinoSeed {
            slug: "iguanodon".into(),
            display_name_de: "Iguanodon".into(),
            scientific_name: "Leguan-Zahn".into(),
            period: "Kreide".into(),
            period_start_mya: 126,
            period_end_mya: 113,
            diet: "Pflanzenfresser".into(),
            length_m: 10.0,
            weight_kg: 3400.0,
            continent: "Europa".into(),
            rarity: "common".into(),
            habitat_description: "Early Cretaceous floodplains with lush vegetation.".into(),
        },
        DinoSeed {
            slug: "pachycephalosaurus".into(),
            display_name_de: "Pachycephalosaurus".into(),
            scientific_name: "Dickschaedel-Echse".into(),
            period: "Kreide".into(),
            period_start_mya: 70,
            period_end_mya: 66,
            diet: "Pflanzenfresser".into(),
            length_m: 4.5,
            weight_kg: 450.0,
            continent: "Nordamerika".into(),
            rarity: "uncommon".into(),
            habitat_description: "Hilly Cretaceous terrain with mixed forests.".into(),
        },
        DinoSeed {
            slug: "archaeopteryx".into(),
            display_name_de: "Archaeopteryx".into(),
            scientific_name: "Urvogel".into(),
            period: "Jura".into(),
            period_start_mya: 150,
            period_end_mya: 148,
            diet: "Fleischfresser".into(),
            length_m: 0.5,
            weight_kg: 1.0,
            continent: "Europa".into(),
            rarity: "legendary".into(),
            habitat_description: "Jurassic tropical islands with lagoons.".into(),
        },
    ]
}
